<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-03-04 15:46

$extensionPath = t3lib_extMgm::extPath('explanationbox');
return array(
	'tx_explanationbox_tca' => $extensionPath . 'class.tx_explanationbox_tca.php',
	'tx_explanationbox_pi1' => $extensionPath . 'pi1/class.tx_explanationbox_pi1.php',
	'tx_explanationbox_pi1_wizicon' => $extensionPath . 'pi1/class.tx_explanationbox_pi1_wizicon.php',
);
?>